version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "10:00"
  open-pull-requests-limit: 10
  labels:
  - dependencies
  ignore:
  - dependency-name: ember-cli
    versions:
    - ">= 0"
  - dependency-name: eslint-plugin-ember
    versions:
    - 10.4.0
  - dependency-name: eslint-plugin-unicorn
    versions:
    - 29.0.0
    - 30.0.0
  - dependency-name: ember-template-lint
    versions:
    - 2.20.0
    - 3.0.0
    - 3.0.1
    - 3.1.1
    - 3.2.0
  - dependency-name: eslint-config-prettier
    versions:
    - 8.0.0
    - 8.1.0
  - dependency-name: ember-source
    versions:
    - 3.25.0
    - 3.26.0
  - dependency-name: typescript
    versions:
    - 4.1.4
