engines:
  duplication:
    enabled: true
    exclude_paths:
    - tests/dummy/app/controllers/**
    - tests/integration/**
    config:
      languages:
      - javascript:
  csslint:
    enabled: true

ratings:
  paths:
  - "**.js"
  - "**.md"
  - "**.css"

exclude_paths:
- "config/**"
- "node_modules/**"
- "vendor/**"
- "*.lock"
